### ISSUE TITLE
holiday_jp-go再始動

### ISSUE THREAD

**Issue by k1LoW** [holiday-jp/holiday_jp-go#6]
@holiday-jp/maintainers 

私もGoが書けるようになったので、holiday_jp-goも最新の祝日に追従させていきたいと思っています。

https://github.com/holiday-jp/holiday_jp-go/issues/4 というような素晴らしい提案もあるので、うまく取り入れられるようにしたいです。

今のところ実施したいことは以下です。

- [x] Go Modules対応
- [ ] YAMLを読み込む形ではなく、YAMLからGoコードをジェネレートする形にする（statikからの脱却）
- [x] GitHub Actions対応

もし何かご意見あればよろしくお願いいたします。
2020/12/10くらいから作業をしたいと思います。

**Comment by okitan** [comment]
go 1.16 から statik じゃなくても embed できるようになるので、そうなったら(来年2月頃）また PR を出そうと考えていたところでした

**Comment by k1LoW** [comment]
@okitan 反応できていなくてすみません！先ほどActions対応のPRを取り込みました！ありがとうございます！

> go 1.16 から statik じゃなくても embed できるようになるので

YAMLをembedして読むよりYAMLからGoのコードを生成したほうがYAMLを読み込む処理がなくなる分パフォーマンス的にも良いと考えていますがいかがでしょう？

**Comment by k1LoW** [comment]
取り急ぎ最新のデータセット（v1.3.0）に追従しました

**Comment by okitan** [comment]
パフォーマンスとしては generate するほうが良いでしょうね（どちらにしてもそんなに気にする程度ではないと思います）
コードを生成する分仕組みが複雑になるのがデメリットですが、他の言語に比べgoはgenerateすることが一般的ですし、特に懸念はないです

**Comment by k1LoW** [comment]
> どちらにしてもそんなに気にする程度ではないと思います

おっしゃる通りですねえ。。

**Comment by k1LoW** [comment]
YAMLを抱えてもgenerateしてもあまり差がないという点に同意なのでここでCloseします
